name: AutoParser deploy
on: [push]
jobs:
  Deploy-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install requirements
      - run: pip install -r requirements.txt
      - name: Run tests
      - run: coverage run tests.py
      - name: Tests report
      - run: coverage report